import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Instrument_Serif, DM_Mono } from "next/font/google"
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { TanstackProvider } from "@/providers/TanstackProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const serif = Instrument_Serif({ variable: "--font-serif", subsets: ["latin"], weight: "400", style: ["normal","italic"] })
const mono  = DM_Mono({ variable: "--font-mono", subsets: ["latin"], weight: ["300","400","500"] })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${serif.variable} ${mono.variable} antialiased`}>
        <ThemeProvider>
          <TanstackProvider>
            <div className="min-h-screen min-w-full">
              {children}
            </div>
          </TanstackProvider>
        </ThemeProvider>
      </body>
    </html >
  );
}
