import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Serif, DM_Mono } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/_providers/ThemeProvider";
import { TanstackProvider } from "@/_providers/TanstackProvider";
import { verifySession } from "@/_lib/authSession";
import { SessionProvider } from "@/_providers/SessionProvider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const serif = Instrument_Serif({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
});

const mono = DM_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await verifySession();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${serif.variable} ${mono.variable} antialiased`}
      >
        <SessionProvider defaultValue={session}>
          <ThemeProvider>
            <TanstackProvider>
              <Toaster />
              {children}
            </TanstackProvider>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}